# Generated by Django 2.1.5 on 2019-01-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmt',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
