# Generated by Django 2.1.5 on 2019-01-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('contents', models.TextField()),
                ('desc', models.CharField(max_length=300, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='upload')),
                ('publicity', models.BooleanField(default=0)),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acticle.acticle')),
            ],
            options={
                'db_table': 'acticle',
            },
        ),
    ]
