# Generated by Django 2.1.5 on 2019-01-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acticle.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.RemoveField(
            model_name='acticle',
            name='column',
        ),
        migrations.AddField(
            model_name='acticle',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acticle.Category'),
        ),
    ]
