# Generated by Django 2.1.5 on 2019-01-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0006_category_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
