# Generated by Django 2.1.5 on 2019-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0007_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
