# Generated by Django 2.1.5 on 2019-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0009_auto_20190111_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CID',
            field=models.IntegerField(default=0),
        ),
    ]
