# Generated by Django 2.1.5 on 2019-01-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0010_category_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CID',
        ),
    ]
