# Generated by Django 2.1.5 on 2019-01-11 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0011_remove_category_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='acticle',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acticle',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
