# Generated by Django 2.1.5 on 2019-01-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0012_auto_20190111_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acticle',
            old_name='publicity',
            new_name='visibility',
        ),
    ]
