# Generated by Django 2.1.5 on 2019-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0013_auto_20190111_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acticle',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
