# Generated by Django 2.1.5 on 2019-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0014_auto_20190111_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acticle',
            name='contents',
            field=models.TextField(default='无'),
        ),
    ]
