# Generated by Django 2.1.5 on 2019-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0015_auto_20190112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acticle',
            name='tags',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='acticle',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
