# Generated by Django 2.1.5 on 2019-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticle', '0016_auto_20190112_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(default='无', max_length=200),
        ),
    ]
